### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by judemont** [AsteroidusTv/Rock-Paper-Scissors-Rust#1]
Is worst

**Comment by AsteroidusTv** [comment]
Sorry but I am not able to accept your Issue I am not part of the horrible community of people who code in high level languages.

**Comment by judemont** [comment]
Python c'est ni trop au niveau, ni trop bas niveau.

C'est pour ça que c'est bien, pasque c'est pas trop au niveau non plus..

**Comment by AsteroidusTv** [comment]
DONT DO ANYTHING ELSE LANGUAGE
